name: Dynamiccheck

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: valgrind install
      run: sudo apt-get updates 
           sudo apt-get install valgrind
    - name: dynamic-check
      run: make dynamiccheck 3_implementation
    
