name: dynamiccheck

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: valgrind install
      run: apt-get install valgrind
    - name: dynamiccheck
      run: make dynamiccheck -C 3_implementation
